name: ${project.name}
version: ${project.version}
main: ${project.mainClass}
author: ${project.author}
api-version: 1.13
permissions:
   autopickup.*:
      default: op
commands:
   autopick:
      usage: /autopick reload
      permission: autopickup.reload